// Generated by protoc-gen-piste-swift
// Source: Proto/piste.proto

import Combine
import SwiftProtobuf

public enum PisteGetServicesService: CallPisteService {
    public static let path: String = "Piste.GetServices"

    public typealias Request = Google_Protobuf_Empty
    public typealias Response = PisteGetServicesResponse
}

public enum PisteGetInformationService: CallPisteService {
    public static let path: String = "Piste.GetInformation"

    public typealias Request = Google_Protobuf_Empty
    public typealias Response = PisteGetInformationResponse
}

